resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: HelloAppIntegration         
      path: michaelyamit/hello-app  
      branches:
        include: main
        
  - name: dbp_image
    type: Image
    configuration:
      registry: ArtifactoryIntegration      
      sourceRepository: docker_local   # required if registry is Artifactory
      region: eu-central-1
      imageName: amitmichaely.jfrog.io/docker-local/hello-app  # replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build
    type: BuildInfo
    configuration:
      sourceArtifactory:  ArtifactoryIntegration
      buildName:  res_<resource_name>_buildName
      buildNumber: res_<resource_name>_buildNumber
      
  - name: simplehelmRepo_docker
    type: GitRepo
    configuration:
      gitProvider: HelloAppIntegration
      path: michaelyamit/hello-app
      files:
        include: "Dockerfile|server.js|package.json" 
        
  - name: simplehelmDockerImage
    type: Image
    configuration:
      registry: ArtifactoryIntegration
      sourceRepository: docker_local   # required if registry is Artifactory
      region: eu-central-1
      imageName: amitmichaely.jfrog.io/docker-local/hello-app
      imageTag: latest
      
  - name: simplehelmRepo_chart
    type: GitRepo
    configuration:
      gitProvider: HelloAppIntegration
      path: michaelyamit/hello-app
      files:
        include: "vfroghelmchart.*"
        
  - name: vfrog_helm_chart
    type: HelmChart
    configuration:
      sourceArtifactory: ArtifactoryIntegration
      repository: helm-local
      chart: vfroghelmchart
      version: ${run_number}
      
      
pipelines:
  - name: pipeline_dbp2
    configuration:
      nodePool: u18-static
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: amitmichaely.jfrog.io/docker-local/hello-app  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: ArtifactoryIntegration 
            
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: ArtifactoryIntegration   
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image
            
      - name: build_info
        type: PublishBuildInfo
        configuration:
          #inherits from bash
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build
            
      - name: scan
        type: XrayScan
        configuration:
          #inherits from bash
          failOnScan: false       
          inputResources:
            - name: dbp_build           # required
              trigger: true
     
      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          helmVersion: 3
          chartPath: vfroghelmchart
          inputSteps:
            - name: docker_push
          inputResources:
            - name: dbp_repo
          outputResources:
            - name: vfrog_helm_chart
          
        execution:
          onStart:
            - export HELM_VERSION="3.4.1"
            - curl -LO "https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - tar -xzf "helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - ln -sf "$PWD/linux-amd64/helm" /usr/local/bin/helm
            - ln -sf "$PWD/linux-amd64/helm" /usr/local/bin/helm3      
      
      - name: deploy_helm_chart
        type: HelmDeploy
        configuration:
          helmVersion: 3
          valueFilePaths:
            - values.yaml
          releaseName: vfrog
          
          integrations:
            - name: GCPIntegration
            - name: KubernetesIntegration
          inputSteps:
            - name: publish_helm_chart
          flags: --namespace dev --set image.repository=amitmichaely.jfrog.io/docker-local/hello-app --set image.tag=${run_number}          
          inputResources:
            - name: vfrog_helm_chart
          
        execution:
          onStart:
            - export HELM_VERSION="3.4.1"
            - curl -LO "https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - tar -xzf "helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - ln -sf "$PWD/linux-amd64/helm" /usr/local/bin/helm
            - ln -sf "$PWD/linux-amd64/helm" /usr/local/bin/helm3 
            - gcloud app update
            - gcloud container clusters get-credentials vfrog --zone europe-west1-c --project vfrog-project
