resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: HelloAppIntegration         
      path: michaelyamit/hello-app  
      branches:
        include: main
        
  - name: dbp_image
    type: Image
    configuration:
      registry: ArtifactoryIntegration      
      sourceRepository: docker_local   # required if registry is Artifactory
      region: eu-central-1
      imageName: amitmichaely.jfrog.io/docker-local/hello-app  # replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build
    type: BuildInfo
    configuration:
      sourceArtifactory:  ArtifactoryIntegration
      buildName:  res_<resource_name>_buildName
      buildNumber: res_<resource_name>_buildNumber
      
pipelines:
  - name: pipeline_dbp
    configuration:
      nodePool: u18-static
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: amitmichaely.jfrog.io/docker-local/hello-app  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: ArtifactoryIntegration   
            
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: ArtifactoryIntegration   
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image
            
      - name: scan
        type: XrayScan
        configuration:
          #inherits from bash
          failOnScan: false       
          inputResources:
            - name: dbp_build           # required
              trigger: false
              
      - name: build_info
        type: PublishBuildInfo
        configuration:
          #inherits from bash
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build
            
 

