apiVersion: v1
kind: Service
metadata:
  name: {{ include "vfroghelmchart.fullname" . }}
  labels:
    {{- include "vfroghelmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "vfroghelmchart.selectorLabels" . | nindent 4 }}
